apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  versions:
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - storageClass
              properties:
                partitions:
                  type: integer
                  minimum: 1
                  maximim: 1024
                  default: 1
                storageClass:
                  type: object
                  required:
                    - name
                  properties:
                    class:
                      type: string
                    group:
                      type: string
                    version:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                readyPartitions:
                  type: integer