apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: members.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Member
    listKind: MemberList
    plural: members
    singular: member
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - properties
          properties:
            properties:
              type: object
              required:
                - metadata
                - service
                - port
              properties:
                metadata:
                  type: object
                  required:
                    - name
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                service:
                  type: string
                port:
                  type: integer