apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: partitions.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Partition
    listKind: PartitionList
    plural: partitions
    singular: partition
  versions:
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - partitionId
                - serviceName
              properties:
                partitionId:
                  type: integer
                  min: 1
                serviceName:
                  type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean