apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: primitives.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Primitive
    listKind: PrimitiveList
    plural: primitives
    singular: primitive
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - properties
          properties:
            properties:
              type: object
              required:
                - metadata
                - type
              properties:
                metadata:
                  type: object
                  required:
                    - name
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                type:
                  type: string