# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1
scope: Cluster
clusterDomain: ""

image:
  registry: ""
  repository: atomix/atomix-gossip-storage-controller
  tag: v0.1.2
  pullPolicy: IfNotPresent
  pullSecrets: []

node:
  image:
    registry: ""
    repository: atomix/atomix-gossip-storage-node
    tag: v0.1.2
    pullPolicy: IfNotPresent
    pullSecrets: []

driver:
  image:
    registry: ""
    repository: atomix/atomix-gossip-storage-driver
    tag: v0.1.2
    pullPolicy: IfNotPresent
    pullSecrets: []
