apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftstorageclasses.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftStorageClass
    listKind: RaftStorageClassList
    plural: raftstorageclasses
    singular: raftstorageclass
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer
                  minmum: 1
                  maximum: 9
                  default: 1
                partitionsPerCluster:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  default: 1
                volumeClaimTemplates:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - spec
                      properties:
                        metadata:
                          type: object
                          properties:
                            name:
                              type: string
                              default: ''
                        spec:
                          type: object
                          properties:
                            accessModes:
                              type: array
                              items:
                                type: string
                                default: ''
                            storageClassName:
                              type: string
                              default: ''
                            resources:
                              type: object
                              properties:
                                requests:
                                  type: object
                                  properties:
                                    storage:
                                      type: string
                                      default: ''