# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq (.Values.scope | lower) "cluster" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "atomix-gossip-storage.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-gossip-storage.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "atomix-gossip-storage.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
