# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "atomix-gossip-storage.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ template "atomix-gossip-storage.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "atomix-gossip-storage.fullname" . }}
    spec:
      serviceAccountName: {{ template "atomix-gossip-storage.fullname" . }}-controller
      containers:
        - name: atomix-gossip-storage-controller
          # Replace this with the built image name
          image: {{ include "atomix-gossip-storage.imagename" .Values.image | quote }}
          {{- if eq (.Values.scope | lower) "namespace" }}
          args:
          - {{ .Release.Namespace }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            exec:
              command:
              - stat
              - /tmp/atomix-controller-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
          - name: CONTROLLER_NAME
            value: {{ template "atomix-gossip-storage.fullname" . }}-controller
          - name: CONTROLLER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CLUSTER_DOMAIN
            value: {{ .Values.clusterDomain }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEFAULT_NODE_V2BETA1_IMAGE
            value: {{ include "atomix-gossip-storage.imagename" .Values.node.image | quote }}