# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v2beta1
kind: StoragePlugin
metadata:
  name: gossip.storage.atomix.io
spec:
  protocol:
    group: storage.atomix.io
    kind: GossipProtocol
  drivers:
  - version: v2beta1
    image: {{ include "atomix-gossip-storage.imagename" .Values.driver.image | quote }}
    config:
      group: storage.atomix.io
      kind: GossipConfig