# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "atomix-controller.fullname" . }}-config
data:
  logging.yaml: |-
    loggers:
      root:
        level: debug
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        type: stdout
        stdout: {}