{{- if eq (.Values.scope | lower) "namespace" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "atomix-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-controller.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "atomix-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}