apiVersion: v1
kind: Service
metadata:
  name: {{ template "atomix-controller.fullname" . }}
  labels:
    name: {{ template "atomix-controller.fullname" . }}
spec:
  selector:
    name: {{ template "atomix-controller.fullname" . }}
  ports:
  - name: control
    port: 5679
  - name: webhook
    port: 443
    targetPort: 443