# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

scope: Cluster

image:
  registry: ""
  repository: atomix/atomix-controller
  tag: v0.6.2
  pullPolicy: IfNotPresent
  pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/atomix-controller-init-certs
    tag: v0.6.2
    pullPolicy: IfNotPresent
    pullSecrets: []

broker:
  image:
    registry: ""
    repository: atomix/atomix-broker
    tag: v0.6.2
    pullPolicy: IfNotPresent
    pullSecrets: []
