{{- if eq (.Values.scope | lower) "cluster" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
