{{- if eq (.Values.scope | lower) "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
roleRef:
  kind: Role
  name: {{ template "atomix-memory-storage.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}