# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v2beta1
kind: StoragePlugin
metadata:
  name: memory.storage.atomix.io
spec:
  protocol:
    group: storage.atomix.io
    kind: MemoryStore
  drivers:
  - version: v2beta1
    image: {{ include "atomix-memory-storage.imagename" .Values.driver.image | quote }}