apiVersion: atomix.io/v2beta1
kind: StoragePlugin
metadata:
  name: memory.storage.atomix.io
spec:
  protocol:
    group: storage.atomix.io
    kind: MemoryStore
  drivers:
  - version: v2beta1
    image: {{ include "atomix-memory-storage.imagename" .Values.driver.image | quote }}