apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redistorageclasses.storage.cloud.atomix.io
spec:
  group:  storage.cloud.atomix.io
  names:
    kind: RedisStorageClass
    listKind: RedisStorageClassList
    plural: redistorageclasses
    singular: redisstorageclass
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
  subresources:
    status: {}