# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftgroups.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftGroup
    listKind: RaftGroupList
    plural: raftgroups
    singular: raftgroup
  scope: Namespaced
  versions:
  - name: v2beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              groupId:
                type: integer
                minumum: 1
              quorumSize:
                type: integer
              readReplicas:
                type: integer
              heartbeatPeriod:
                type: string
              electionTimeout:
                type: string
              snapshotEntryThreshold:
                type: integer
                minimum: 0
              compactionRetainEntries:
                type: integer
                minimum: 0
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
              leader:
                type: string
              term:
                type: integer
    additionalPrinterColumns:
    - name: Leader
      type: string
      description: The current leader for the partition
      jsonPath: .status.leader
    - name: Term
      type: integer
      description: The current term for the partition
      jsonPath: .status.term
    - name: Status
      type: string
      description: The partition state
      jsonPath: .status.state