{{- if eq (.Values.scope | lower) "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "atomix-raft-storage.fullname" . }}-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/ephemeralcontainers
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - cloud.atomix.io
  - storage.cloud.atomix.io
  - atomix.io
  - primitives.atomix.io
  - storage.atomix.io
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}