# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq (.Values.scope | lower) "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "atomix-raft-storage.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-raft-storage.fullname" . }}-controller
roleRef:
  kind: Role
  name: {{ template "atomix-raft-storage.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}